### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dmitry12** [percy/cli#735]
## The problem

After upgrading from `@percy/storybook": "^3.3.1` to `"@percy/cli": "^1.0.0-beta.73"`, `"@percy/storybook": "^4.1.0"` and running it on github hosted runner I encountered this error:

```
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/home/runner/work/app/app/storybook/node_modules/@percy/core/dist/utils.js:162
      return yield* check(start);
             ^
```

## Environment

- Node version: node 16.13.2
- `@percy/cli` version: 1.0.0-beta.73
- Version of Percy SDK you're using: 
- If needed, a build or snapshot ID: Build #10120 (Last successful build that was run locally)
- OS version: Ubuntu 20.04.3 LTS (ubuntu-latest)
- Type of shell command-line [interface]: /usr/bin/bash

## Details

- We have ~160 stories in storybook and it always fails on random one. (Usually finishes about 70% of the stories)
- When running locally on more powerful machine it manages to finish, but still fails sometimes with the same error.

## Debug logs

Debug output: https://gist.github.com/dmitry12/fc9d07665b3171dd372857fc9d6bed8e

## Code to reproduce issue

I created repo with 300 sample stories and was able to reproduce the error: https://github.com/dmitry12/percy-bug-repro

```
npm/yarn install
percy storybook --debug ./storybook-static
```

**Comment by cancan101** [comment]
I am also having this error. I was previously on `1.0.0-beta.69` which did not raise the error but does seem to hand indefinitely on:
```
[percy:client] Uploading resource: /percy.1629232245XXX.log... (2ms)
[percy:client] Finalizing snapshot XXX784804... (323ms)
[percy:client] Finalizing snapshot XXX784803... (2ms)
```

**Comment by filipw01** [comment]
@wwilsman I tried pinning `@percy/cli@1.0.0-beta.71` and it was producing the same error

**Comment by cancan101** [comment]
`@percy/cli@1.0.0-beta.71` works for me but then when I made other changes I am still seeing it hanging on the `Finalizing` step.

**Comment by wwilsman** [comment]
I just released [v1.0.0-beta.74](https://github.com/percy/cli/releases/tag/v1.0.0-beta.74) which should hopefully fix the call stack error. 🤞 

@cancan101 if updating doesn't help your hanging issue, maybe it's worth opening another discussion for that

**Comment by cancan101** [comment]
ok, I can confirm that `v1.0.0-beta.74 ` did fix the call stack issue. I have reported #742 with the hanging issue which still exists in the new version.

**Comment by rmknecht** [comment]
I am encountering the same call stack error. Bumping to `v1.0.0-beta.74` did not resolve the issue.

Using `"@percy/storybook": "^4.1.0"` and generating 400+ snapshots

**Comment by wwilsman** [comment]
@rmknecht could you share your error message?

From the original issue, `return yield* check(start);` doesn't exist anymore. So if you're still receiving a stack trace error, it's possible the stack is growing in a different location for a similar reason

**Comment by rmknecht** [comment]
@wwilsman - It looks  my issue was the result of a stale version of `@percy/cli` in my monorepo. After wiping `node_modules` directories and reinstalling with `v1.0.0-beta.74` I am no longer encountering the stack error. All set here 👍

**Comment by filipw01** [comment]
Seems to be working for me. Lots of thanks @wwilsman 🙏

**Comment by wwilsman** [comment]
That's great! Closing this now. 😄

**Comment by dmitry12** [comment]
@wwilsman still encountering the same issue after upgrading to `v1.0.0-beta.74` in example repo.

Package versions:
`@percy/cli: 1.0.0-beta.74`
`@percy/storybook: 4.1.0`

Full debug log: https://gist.github.com/dmitry12/92f9703c7a0deb929bdc621378c4d737

**Comment by Robdel12** [comment]
Hey @dmitry12! I think you're having a caching issue (https://github.com/percy/cli/issues/735#issuecomment-1020618853) 

```
/Users/dmitry/dev/repos/percy-bug-repro/node_modules/@percy/storybook/node_modules/@percy/core/dist/utils.js:162
      return yield* check(start);
```

Is the same stack trace as the original issue and that code no longer exists. This is the new util dist output: 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/2072894/151217752-21e2805d-c005-433b-b3fc-9572f6ad7685.png">
